import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: '#fff',
  },
  imageContainer: {
    alignItems: 'center',
    position: 'relative',
    height: 300,
    marginBottom: 10,
  },
  image: {
    width: '90%',
    height: '100%',
    borderRadius: 20,
  },
  heartButton: {
    position: 'absolute',
    top: 280,
    right: 25,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 8,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  content: {
    padding: 20,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 24,
    color: '#000',
  },
  mapLink: {
    fontFamily: 'Montserrat-SemiBold',
    color: '#4169E1',
    fontSize: 16,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  rating: {
    fontFamily: 'Montserrat-Medium',
    marginLeft: 5,
    color: '#000',
  },
  description: {
    fontFamily: 'Montserrat-Regular',
    color: '#000',
    lineHeight: 20,
    marginBottom: 20,
  },
  conveniencesTitle: {
    fontFamily: 'Montserrat-SemiBold',
    color: '#000',
    fontSize: 22,
    marginBottom: 15,
  },
  conveniences: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 100,
  },
  convenienceItem: {
    alignItems: 'center',
    backgroundColor: '#f0f3fb',
    padding: 12,
    borderRadius: 10,
    width: '22%',
  },
  convenienceText: {
    marginTop: 5,
    color: '#b8b8b8',
    fontSize: 12,
  },
  convenienceIcon: {
    color: '#b8b8b8',
    fontSize: 32,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  price: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#78d5a8',
  },
  labelPrice: {
    fontFamily: 'Montserrat-SemiBold',
    color: '#000',
    fontSize: 16,
  },
  bookButton: {
    width: '62%',
    backgroundColor: '#4169E1',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 20,
    shadowColor: '#4169E1',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  bookButtonText: {
    fontFamily: 'Montserrat-Regular',
    color: '#fff',
    marginRight: 10,
    fontSize: 16,
  },
  cancelButton: {
    width: '62%',
    justifyContent: 'center',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 40,
    borderRadius: 20,
    shadowColor: '#4169E1',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  cancelButtonText: {
    fontFamily: 'Montserrat-Regular',
    color: '#4169E1',
    marginRight: 10,
    fontSize: 16,
  },
  readMoreButton: {
    fontFamily: 'Montserrat-SemiBold',
    color: '#4169E1',
    fontSize: 16,
    marginBottom: 25,
  },
});

export default styles;